"""Create diets and linking tables

Revision ID: b77a16b1871f
Revises: 6aa886c3c859
Create Date: 2024-02-27 17:37:34.516819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b77a16b1871f'
down_revision = '6aa886c3c859'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('restriction_name', sa.Text(), nullable=False),
    sa.Column('endorsement_name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('endorsements',
    sa.Column('diet_id', sa.UUID(), nullable=False),
    sa.Column('restaurant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['diet_id'], ['diets.id'], ),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ),
    sa.PrimaryKeyConstraint('diet_id', 'restaurant_id')
    )
    op.create_table('restrictions',
    sa.Column('diet_id', sa.UUID(), nullable=False),
    sa.Column('eater_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['diet_id'], ['diets.id'], ),
    sa.ForeignKeyConstraint(['eater_id'], ['eaters.id'], ),
    sa.PrimaryKeyConstraint('diet_id', 'eater_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('restrictions')
    op.drop_table('endorsements')
    op.drop_table('diets')
    # ### end Alembic commands ###
